image: docker:24.0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  IMAGE_VERSION: ""

services:
  - docker:dind

before_script:
  - export IMAGE_VERSION=$(date +"%y-%m-%d")
  - |
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch-builder --use
  - docker buildx inspect --bootstrap

containers:
  stage: build
  script:
    - cd server
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:latest --push .
    - docker logout
    - echo -n $DOCKERHUB_ACCESS_TOKEN | docker login -u madmachinations --password-stdin
    - docker tag $CI_REGISTRY_IMAGE:latest madmachinations/ha-alexa-shopping-list-sync:$IMAGE_VERSION
    - docker push madmachinations/ha-alexa-shopping-list-sync:$IMAGE_VERSION
    - docker tag $CI_REGISTRY_IMAGE:latest madmachinations/ha-alexa-shopping-list-sync:latest
    - docker push madmachinations/ha-alexa-shopping-list-sync:latest
  only:
    - main