image: docker:18

services:
  - name: docker:dind

stages:
  - build

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

x86:
  stage: build
  only:
    - main
  script:
    - cd server
    - docker build -t alexa_shopping_list_sync:$CI_COMMIT_SHA .
    - docker tag alexa_shopping_list_sync:$CI_COMMIT_SHA alexa_shopping_list_sync:latest
    - docker push alexa_shopping_list_sync:latest

arm64:
  stage: build
  tags:
    - saas-linux-medium-arm64
  only:
    - main
  script:
    - cd server
    - docker build -t alexa_shopping_list_sync:$CI_COMMIT_SHA .
    - docker tag alexa_shopping_list_sync:$CI_COMMIT_SHA alexa_shopping_list_sync:latest
    - docker push alexa_shopping_list_sync:latest
