image: docker:24.0

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1

services:
  - docker:dind

before_script:
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  - |
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name multiarch-builder --use
  - docker buildx inspect --bootstrap

build_containers:
  stage: build
  script:
    - cd server
    - docker buildx build --platform linux/amd64,linux/arm64 -t $CI_REGISTRY_IMAGE:latest --push .
  only:
    - main